#!/usr/bin/bash

pushd /home/jlourenco/tparreira/benchbase-postgres
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_NO100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_NO100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_NO100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_NO100 --create=true --load=true --execute=true -b tpcc_lsd
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_NO100 --create=true --load=true --execute=true -b tpcc_lsd
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_NO100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_NO100 --create=true --load=true --execute=true -b tpcc_lsd
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc_lsd
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc_lsd
java -jar benchbase.jar -c /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_Pay100.xml -d /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_Pay100 --create=true --load=true --execute=true -b tpcc_lsd
popd
python3 /home/jlourenco/tparreira/benchbase-postgres/scripts/plot_data.py /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc
python3 /home/jlourenco/tparreira/benchbase-postgres/scripts/plot_data.py /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_NO100 /home/jlourenco/tparreira/benchbase-postgres/tpcc
python3 /home/jlourenco/tparreira/benchbase-postgres/scripts/plot_data.py /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca1_Ter10_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter10_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca1_Ter10_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter10_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc
python3 /home/jlourenco/tparreira/benchbase-postgres/scripts/plot_data.py /home/jlourenco/tparreira/benchbase-postgres/tpcc/base/psql_Sca10_Ter1_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc/lsd/psql_Sca10_Ter1_Dur120_Pay100 /home/jlourenco/tparreira/benchbase-postgres/tpcc
